# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0.xci
# IP: The module: 'zcu102_es2_zynq_ultra_ps_e_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_es2_zynq_ultra_ps_e_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_es2_zynq_ultra_ps_e_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0.xci
# IP: The module: 'zcu102_es2_zynq_ultra_ps_e_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_es2_zynq_ultra_ps_e_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /scratch/xbrbbot/yocto/2018.1/bsps/xilinx-zcu102-zu9-es2-rev1.0-2018.1/hw_proj/xilinx-zcu102-zu9-es2-rev1.0-2018.1/xilinx-zcu102-zu9-es2-rev1.0-2018.1.srcs/sources_1/bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu102_es2_zynq_ultra_ps_e_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
