# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xilinx-zcu102-zu9-es2-rev1.0-2018.1.xdc

# Block Designs: bd/zcu102_es2/zcu102_es2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_es2 || ORIG_REF_NAME==zcu102_es2} -quiet] -quiet

# IP: bd/zcu102_es2/ip/zcu102_es2_zynq_ultra_ps_e_1_0/zcu102_es2_zynq_ultra_ps_e_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu102_es2_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==zcu102_es2_zynq_ultra_ps_e_1_0} -quiet] -quiet

# XDC: bd/zcu102_es2/zcu102_es2_ooc.xdc
